### ISSUE TITLE
多输入输出分配内存

### ISSUE THREAD

**Issue by budaLi** [qq995431104/Pytorch2TensorRT#5]
您好，看到inference时只是支持单输入 和单输出的内存分配，请问多输入或者多输出如何进行内存分配呢？

**Comment by qq995431104** [comment]
参考：https://github.com/qq995431104/Pytorch2TensorRT/issues/3#issuecomment-698201773

**Comment by budaLi** [comment]
您好，我的意思是 输入为[1,c,h,w] ，输出为[1，100] ,[1,200],[1,300]这样子，不是在batch的维度

**Comment by qq995431104** [comment]
那就按1batch的方式来就行啊，不管你的输出是什么尺寸，只要分配对应内存就行了。不管[1, 100]，还是[1, 100, 100]还是[1, 100, 100, 100, ......]

**Comment by budaLi** [comment]
https://github.com/TrojanXu/onnxparser-trt-plugin-sample   参考这个工程的代码可解决  感谢您的回复~
